'use client'

import { useState, useEffect } from 'react'

interface Props {
  userType: 'conveyancer' | 'lawyer'
  onAccept: () => void
}

/**
 * ProfessionalDisclaimer
 *
 * Modal that fires every time a conveyancer or lawyer opens a property report.
 * Cannot be permanently dismissed — no "don't show again" option.
 * This protects PropertyOwl AI legally by creating an acknowledged disclaimer
 * on every professional use session.
 */
export default function ProfessionalDisclaimer({ userType, onAccept }: Props) {
  const [visible, setVisible] = useState(true)
  const [checked, setChecked] = useState(false)

  // Prevent background scroll while modal is open
  useEffect(() => {
    if (visible) {
      document.body.style.overflow = 'hidden'
    }
    return () => { document.body.style.overflow = '' }
  }, [visible])

  if (!visible) return null

  const typeLabel = userType === 'conveyancer' ? 'Conveyancer' : 'Lawyer'

  function handleAccept() {
    if (!checked) return
    setVisible(false)
    onAccept()
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />

      {/* Modal */}
      <div className="relative bg-white rounded-2xl shadow-2xl max-w-lg w-full overflow-hidden">

        {/* Header */}
        <div className="bg-[#E8001D] px-6 py-5">
          <div className="flex items-center gap-3">
            <span className="text-2xl">⚖️</span>
            <div>
              <h2 className="text-white font-black text-lg leading-tight">
                Professional Use Notice
              </h2>
              <p className="text-red-100 text-xs mt-0.5">
                Required acknowledgement — {typeLabel} access
              </p>
            </div>
          </div>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-4">

          <p className="text-gray-700 text-sm leading-relaxed">
            The analysis you are about to view is <strong>generated by artificial intelligence</strong> to
            assist your professional review of this property. It is intended as a
            starting point for your own analysis, not a substitute for it.
          </p>

          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 space-y-2">
            <p className="text-xs font-bold text-amber-800 uppercase tracking-wide">
              Important — please read before proceeding
            </p>
            <ul className="space-y-1.5 text-xs text-amber-700 leading-relaxed">
              <li className="flex gap-2">
                <span className="text-amber-500 flex-shrink-0 mt-0.5">•</span>
                This AI analysis has <strong>not been independently verified</strong> and may contain errors,
                omissions or misinterpretations.
              </li>
              <li className="flex gap-2">
                <span className="text-amber-500 flex-shrink-0 mt-0.5">•</span>
                It <strong>does not constitute legal advice</strong> and must not be presented to clients
                as such.
              </li>
              <li className="flex gap-2">
                <span className="text-amber-500 flex-shrink-0 mt-0.5">•</span>
                You must <strong>validate all findings</strong> within your own professional judgement
                and against the source documents before acting on them.
              </li>
              <li className="flex gap-2">
                <span className="text-amber-500 flex-shrink-0 mt-0.5">•</span>
                Any client email drafts generated are <strong>templates only</strong> — review and
                edit before sending.
              </li>
            </ul>
          </div>

          <div className="bg-gray-50 border border-gray-200 rounded-xl p-3 text-xs text-gray-500 leading-relaxed">
            PropertyOwl AI is provided as an information tool. Neither PropertyOwl AI nor
            its operators accept liability for decisions made based on AI-generated analysis.
            Always exercise your professional duty of care.
          </div>

          {/* Acknowledgement checkbox */}
          <label className="flex items-start gap-3 cursor-pointer group">
            <div className="flex-shrink-0 mt-0.5">
              <input
                type="checkbox"
                checked={checked}
                onChange={e => setChecked(e.target.checked)}
                className="w-4 h-4 accent-[#E8001D] cursor-pointer"
              />
            </div>
            <span className="text-sm text-gray-700 leading-relaxed group-hover:text-gray-900 transition-colors">
              I understand that this analysis is AI-generated, for my professional reference only,
              and does not constitute legal advice. I will validate all findings before acting on them.
            </span>
          </label>
        </div>

        {/* Footer */}
        <div className="px-6 pb-6">
          <button
            onClick={handleAccept}
            disabled={!checked}
            className={`w-full py-3 rounded-xl font-bold text-sm transition-all ${
              checked
                ? 'bg-[#E8001D] hover:bg-[#C4001A] text-white shadow-sm'
                : 'bg-gray-100 text-gray-400 cursor-not-allowed'
            }`}
          >
            {checked ? 'I understand — show me the analysis →' : 'Please tick the box above to continue'}
          </button>
          <p className="text-center text-xs text-gray-400 mt-3">
            This notice appears every session as required by our terms of service.
          </p>
        </div>

      </div>
    </div>
  )
}
