'use client'

import { useState } from 'react'

interface Props {
  userType: 'conveyancer' | 'lawyer'
  onAccept: () => void
}

export default function ProfessionalDisclaimer({ userType, onAccept }: Props) {
  const [checked, setChecked] = useState(false)
  const typeLabel = userType === 'lawyer' ? 'Lawyer' : 'Conveyancer'

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: 'rgba(0,0,0,0.65)', backdropFilter: 'blur(6px)' }}
    >
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden">

        {/* Header */}
        <div className="bg-[#E8001D] px-6 py-5">
          <div className="flex items-center gap-3">
            <span className="text-2xl leading-none">⚖️</span>
            <div>
              <h2 className="text-lg font-bold text-white leading-tight">Professional Use Notice</h2>
              <p className="text-red-200 text-sm mt-0.5">Required acknowledgement — {typeLabel} access</p>
            </div>
          </div>
        </div>

        {/* Scrollable body */}
        <div className="p-6 space-y-4 max-h-[70vh] overflow-y-auto">

          <p className="text-sm text-gray-700 leading-relaxed">
            The analysis you are about to view is <strong>generated by artificial intelligence</strong> to
            assist your professional review of this property. It is intended as a starting point for your
            own analysis, not a substitute for it.
          </p>

          {/* Key points */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
            <p className="text-xs font-bold text-amber-800 uppercase tracking-wide mb-3">
              Important — please read before proceeding
            </p>
            <div className="space-y-2.5">
              {[
                { pre: 'This AI analysis has', bold: 'not been independently verified', post: 'and may contain errors, omissions or misinterpretations.' },
                { pre: 'It', bold: 'does not constitute legal advice', post: 'and must not be presented to clients as such.' },
                { pre: 'You must', bold: 'validate all findings', post: 'within your own professional judgement and against the source documents before acting on them.' },
                { pre: 'Any client email drafts generated are', bold: 'templates only', post: '— review and edit before sending.' },
              ].map((item, i) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-amber-500 flex-shrink-0 mt-1.5" />
                  <p className="text-xs text-amber-800 leading-relaxed">
                    {item.pre} <strong>{item.bold}</strong> {item.post}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Liability notice */}
          <div className="bg-gray-50 border border-gray-200 rounded-xl p-4">
            <p className="text-xs text-gray-500 leading-relaxed">
              PropertyOwl AI is provided as an information tool. Neither PropertyOwl AI nor its operators
              accept liability for decisions made based on AI-generated analysis. Always exercise your
              professional duty of care.
            </p>
          </div>

          {/* Checkbox */}
          <label className="flex items-start gap-3 cursor-pointer group select-none">
            <div
              onClick={() => setChecked(c => !c)}
              className={`w-5 h-5 rounded border-2 flex-shrink-0 mt-0.5 flex items-center justify-center transition-all cursor-pointer ${
                checked
                  ? 'bg-[#E8001D] border-[#E8001D]'
                  : 'border-gray-300 group-hover:border-gray-500'
              }`}
            >
              {checked && <span className="text-white text-xs font-bold leading-none">✓</span>}
            </div>
            <span className="text-sm text-gray-700 leading-relaxed">
              I understand that this analysis is AI-generated, for my professional reference only,
              and does not constitute legal advice. I will validate all findings before acting on them.
            </span>
          </label>

          {/* CTA button */}
          <button
            onClick={onAccept}
            disabled={!checked}
            className={`w-full py-3 rounded-xl text-sm font-bold transition-all ${
              checked
                ? 'bg-[#E8001D] hover:bg-red-700 text-white shadow-sm'
                : 'bg-gray-100 text-gray-400 cursor-not-allowed'
            }`}
          >
            {checked ? 'Continue to Professional Analysis →' : 'Please tick the box above to continue'}
          </button>

          <p className="text-center text-xs text-gray-400">
            This notice appears every session as required by our terms of service.
          </p>
        </div>
      </div>
    </div>
  )
}
